/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisplayWishlist: typeof import('./components/DisplayWishlist.vue')['default']
    InputItem: typeof import('./components/InputItem.vue')['default']
    InputItemQty: typeof import('./components/InputItemQty.vue')['default']
    ItemSelector: typeof import('./components/ItemSelector.vue')['default']
    LightRays: typeof import('./components/LightRays.vue')['default']
    Material: typeof import('./components/Material.vue')['default']
    MaterialDisplay: typeof import('./components/MaterialDisplay.vue')['default']
    'MaterialSymbols:arrowDownward': typeof import('~icons/material-symbols/arrow-downward')['default']
    'MaterialSymbols:arrowDropdown': typeof import('~icons/material-symbols/arrow-dropdown')['default']
    'MaterialSymbols:arrowDropDown': typeof import('~icons/material-symbols/arrow-drop-down')['default']
    'MaterialSymbols:arrowDropUp': typeof import('~icons/material-symbols/arrow-drop-up')['default']
    'MaterialSymbols:arrowForward': typeof import('~icons/material-symbols/arrow-forward')['default']
    'MaterialSymbols:close': typeof import('~icons/material-symbols/close')['default']
    'MaterialSymbols:starRounded': typeof import('~icons/material-symbols/star-rounded')['default']
    'MaterialSymbols:viewInAr': typeof import('~icons/material-symbols/view-in-ar')['default']
    'MaterialSymbols:viewInArOff': typeof import('~icons/material-symbols/view-in-ar-off')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Mineralogy: typeof import('~icons/mi/neralogy')['default']
    Particles: typeof import('./components/Particles.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Timeline: typeof import('./components/Timeline.vue')['default']
    VueCal: typeof import('vue-cal')['VueCal']
  }
}
